### ISSUE TITLE
Compilation error on Debian

### ISSUE THREAD

**Issue by tomcrott** [BeamMP/BeamMP-Launcher#226]
I got an error trying to compile on Pop!_OS 24.04 LTS, but I changed line 41 of /BeamMP-Launcher/src/Network/ from 
` { "get_openssl_verify_result", client.get_verify_result() },` 
to 
`{ "openssl_verify_result", client.get_verify_result() },` 
and it solved the issue.
Just posting this here in case anyone else has the same problem!

**Comment by WiserTixx** [comment]
Could you try building the https://github.com/BeamMP/BeamMP-Launcher/tree/fix-build branch and see if it fixes your issue?

**Comment by Reixeen** [comment]
I am on CachyOS and I also had to change line 41 of /BeamMP-Launcher/src/Network/Http to your 
{ "openssl_verify_result", client.get_verify_result() },

it then built for me
